config/routes.rb
Rails.application.routes.draw do
  
  get 'home/index'

  default_url_options :host => "localhost"
  root 'home#index'

  devise_for :users, :controllers => {:registrations => "users/registrations"}

  resources :users, only: [:index]
  
  resources :projects do
    resources :milestones do
      resources :tasks
    end
  end

end

app/models/milestone.rb
class Milestone < ActiveRecord::Base

	has_many :milestone_project_ids
	has_many :projects , through: :milestone_project_ids

	has_many :milestone_task_ids
	has_many :tasks , through: :milestone_task_ids

	def self.search(search)
	  where("Name ILIKE ?", "%#{search}%") 
	  # where("Description ILIKE ?", "%#{search}%")
	end
	
	paginates_per 4
	max_paginates_per 100

end

app/controllers/milestones_controller.rb
class MilestonesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_milestone, only: [:show, :edit, :update, :destroy]

  # GET /milestones
  # GET /milestones.json
  def index
    # binding.pry
    # @milestones = current_user.milestones
    @project = Project.find(params[:project_id])
    @q = Milestone.ransack(params[:q])
    @q.result.includes(:name).page(params[:page])


    if params[:search]
      @milestones = @project.milestones.search(params[:search]).order("created_at DESC").page(params[:page])
    else
      @milestones = @project.milestones.order('created_at ASC').page(params[:page])
    end
      
  # @milestones = @q.result.includes(:name).page(params[:page])
  end

  # GET /milestones/1
  # GET /milestones/1.json
  def show
    @milestone = Milestone.find(params[:id])
    @project = Project.find(params[:project_id])
  end

  # GET /milestones/new
  def new
    @milestone = Milestone.new
    @project = Project.find(params[:project_id])
  end

  # GET /milestones/1/edit
  def edit
    @milestone = Milestone.find(params[:id])
    @project = Project.find(params[:project_id])
  end

  # POST /milestones
  # POST /milestones.json
  def create

    @project = Project.find(params[:project_id])
    # binding.pry
    @milestone = @project.milestones.create(milestone_params)

    respond_to do |format|
      if @milestone.save
        format.html { redirect_to project_milestones_path, notice: 'Milestone was successfully created.' }
        format.json { render :show, status: :created, location: @milestone }
      else
        format.html { render :new }
        format.json { render json: @milestone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /milestones/1
  # PATCH/PUT /milestones/1.json
  def update
    @project = Project.find(params[:project_id])
    respond_to do |format|
      if @milestone.update(milestone_params)
        format.html { redirect_to project_milestone_path, notice: 'Milestone was successfully updated.' }
        format.json { render :show, status: :ok, location: @milestone }
      else
        format.html { render :edit }
        format.json { render json: @milestone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /milestones/1
  # DELETE /milestones/1.json
  def destroy
    # binding.pry
    @project = Project.find(params[:project_id])
    @milestone.destroy
    respond_to do |format|
      format.html { redirect_to project_milestones_path, notice: 'Milestone was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:project_id])
    end

    def set_milestone
      @milestone = Milestone.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def milestone_params
      params.require(:milestone).permit( :name, :description, :start_date, :end_date)
    end
end

app/helpers/milestones_helper.rb
module MilestonesHelper
end

app/views/milestones/_form.html.erb
<%= form_for [@project,@milestone] do |f| %>
  <% if @milestone.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@milestone.errors.count, "error") %> prohibited this milestone from being saved:</h2>

      <ul>
      <% @milestone.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="item form-group bad">
    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Name :<span class="required">*</span>
    </label>
    <div class="col-md-8 col-sm-8 col-xs-12">
      <%= f.text_field :name , :placeholder => "Name" , :class => "form-control" , :data_validate_length_range =>"6" , :data_validate_words => "2" , :required => "required" , :type => "text"%>
    </div>
    <!-- <div class="alert">please put something here</div> -->
  </div>
  <br>
  <br>
  <br>
  
  <div class="item form-group bad">
    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Description : <span class="required">*</span>
    </label>
    <div class="col-md-8 col-sm-8 col-xs-12">
      <%= f.text_area :description , :class => "form-control" , :placeholder => "Description" , :data_validate_length_range =>"6" , :data_validate_words => "2" , :required => "required" , :type => "text"%>
    </div>
    <!-- <div class="alert">please put something here</div> -->
  </div>
  
  <br>
  <br>
  <br>

  <div class="item form-group bad">
    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Start Date : <span class="required">*</span>
    </label>
    <div class="col-md-8 col-sm-8 col-xs-12">
    <%= f.text_field :start_date , :class => "datepicker form-control" , :placeholder => "Start Date(mm/dd//yyyy)" , :data_validate_length_range =>"6" , :data_validate_words => "2" , :required => "required" %>
   </div>
    <!-- <div class="alert">please put something here</div> -->
  </div>

  <br>
  <br>
  
  <div class="item form-group bad">
    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">End Date : <span class="required">*</span>
    </label>
    <div class="col-md-8 col-sm-8 col-xs-12">
      <%= f.text_field :end_date , :class => "datepicker form-control" , :placeholder => "End Date(mm/dd//yyyy)" , :data_validate_length_range =>"6" , :data_validate_words => "2" , :required => "required" %>
    </div>
    <!-- <div class="alert">please put something here</div> -->
  </div>
  
  <br>
  <br>

  <div class="clearfix"></div>
  
  <div class="col-md-8 col-sm-8 col-xs-12">
    <button class="col-md-offset-3 btn btn-info btn-block" type="submit">Submit</button>
  </div>
<% end %>

<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<script>

$(document).ready(function() {
    $(".datepicker").datepicker({
      dateFormat: "yy-mm-dd"
    });
});

 </script>

app/views/milestones/_search_milestone.html.erb
<%= form_tag(project_milestones_path, :method => "get", id: "search-form" , :class => "form-search form-horizontal pull-right col-md-3" ) do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search Milestones", :class=> "form-control" %>
  <!-- <i class="fa fa-search project-search"></i> -->
<% end %>
<div class="clearfix"></div>

app/views/milestones/edit.html.erb
<div class="col-md-6 col-sm-12 col-xs-12 col-md-offset-3">
  <div class="pull-right">
    <%= link_to 'Show', project_milestone_path(project_id: @project.id , id: @milestone.id) , :class => "" %> |
    <%= link_to 'Add Task', project_milestone_tasks_path(project_id: @project.id, milestone_id: @milestone.id) , :class => "" %> |
    <%= link_to 'Back', project_milestones_path(project_id: @project.id) , :class => "" %>
    <br>  
    <br>
  </div>
</div>
<div class="col-md-6 col-sm-12 col-xs-12 col-md-offset-3">
  <div class="x_panel">
  	<div class="x_content">
      <div class="dashboard-widget-content">
        <div class="col-md-6 col-md-offset-3 hidden-small">
      		<h2 class="line_30">Editing Milestone</h2>
    		</div>
    	</div>
  	</div>
		<br>
		<div class="text-center">
      <div class="row">
        <div class="col-lg-12 col-md-6 col-xs-6">
          <div class="form-group">
            <%= render 'form' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/milestones/index.html.erb
<div class="container">
  <div class="pull-left">
    <i class="fa fa-arrow-left"></i> <%= link_to "Go To Projects"  , projects_path %>
  </div>
  <div class="row tile_count">
    <%= render 'search_milestone' %>
    <div class="panel-heading flex-box flex-vertical-center-align justify-content-space-between">
      <h3 class="col-md-9">Milestones</h3>
    </div>
    <div class="container">
      <div class="col-md-12">
       <table class="table table-list-search table-hover">
          <div class="pull-right">
            <% if can? :manage, Milestone %>
              <%= link_to 'New Milestone', new_project_milestone_path(@project) , :class => "btn btn-info" %>
            <% end %>
          </div>
          <br>
          <br>
          <br>
          <thead>
            <tr>
              <th><%= sort_link(@q, :name) %></th>
              <th>Description</th>
              <th>Start date</th>
              <th>End date</th>
              <th colspan="1" style="width: 260px;">Manage</th>
            </tr>
          </thead>
          <tbody>
          <%if @q.result.present? %>
            <% @q.result.each do |milestone| %>
              <tr>
                <td><%= link_to milestone.name , project_milestone_path(project_id: milestone.projects.last.id , id: milestone.id) %></td>
                <td><%= milestone.description %></td>
                <td><%= milestone.start_date %></td>
                <td><%= milestone.end_date %></td>
                <td><%= link_to raw("<span class='fa fa-wrench'></span>Edit"), edit_project_milestone_path(project_id: milestone.projects.last.id , id: milestone.id) , :class => "btn btn-info btn-sm" %> &nbsp; &nbsp;
                    <%= link_to raw("<span class='fa fa-trash'></span>Delete"), project_milestone_path(project_id: milestone.projects.last.id , id: milestone.id), method: :delete, data: { confirm: 'Are you sure?' } , :class => "btn btn-danger btn-sm" %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%= paginate @milestones %>
        <%end%>
        <br>
        <br>
      </div>
    </div>
  </div>
</div> 

app/views/milestones/new.html.erb
<div class="col-md-6 col-sm-3 col-xs-12 col-md-offset-3">
  <div class="pull-right">
    <%= link_to 'Back', project_milestones_path(project_id: @project.id) , :class => "" %>
    <br>
    <br>
  </div>
</div>
<div class="col-md-6 col-sm-3 col-xs-12 col-md-offset-3">
  <section class="panel">
    
		<div class="x_title">
      <h3 class="text-center"><strong>New Milestone</strong></h3>
      <div class="clearfix"></div>
		</div>
		<br>
    <div class="panel-body">
      <div class="text-center">
        <div class="row">
          <div class="col-lg-12 col-md-6 col-xs-6">
            <div class="form-group">
      				<%= render 'form' %>
      			</div>	
      		</div>
      	</div>
      </div>
    </div>
  </section>
</div>

app/views/milestones/show.html.erb
<div class="col-md-6 col-sm-3 col-xs-12 col-md-offset-3">
  <div class="pull-right">
    <%= link_to 'Edit', edit_project_milestone_path(id: @milestone.id , project_id: @project.id) , :class => ""  %> |
    <%= link_to 'Back', project_milestones_path(project_id: @project.id) , :class => ""  %> | 
    <%= link_to 'Add Task' , new_project_milestone_task_path(project_id: @project.id , milestone_id: @milestone.id) , :class => "" %> | 
    <%= link_to 'View Tasks' , project_milestone_tasks_path(project_id: @project.id , milestone_id: @milestone.id) , :class => "" %>
    <br>
    <br>
  </div>
</div>
<div class="col-md-6 col-sm-3 col-xs-12 col-md-offset-3">
  <section class="panel">
    
	  <div class="x_title">
      <h2>Milestone Description</h2>
      <div class="clearfix"></div>
    </div>
    <div class="panel-body">
      <h3 class="green"><i class="fa fa-paint-brush"></i> <%= @milestone.name %></h3>
      <br>
      <div class="project_detail">
		    <div class="row">
		      <div class="col-md-12">
						<div class="well col-md-12">
						  Description : <%= @milestone.description %>
						</div>
          </div>
        </div>
				<div class="clearfix"></div>
				<p>
				  <p class="title">Start Date : </p>
				  <p><%= @milestone.start_date %> </p>
				</p>
				<p>
				  <p class="title">End Date : </p>
				  <p><%= @milestone.end_date %> </p>
				</p>
				<br>
			</div>
		</div>
	</section>
</div>