config/routes.rb
Rails.application.routes.draw do
  
  get 'home/index'

  default_url_options :host => "localhost"
  root 'home#index'

  devise_for :users, :controllers => {:registrations => "users/registrations"}

  resources :users, only: [:index]
  
  resources :projects do
    resources :milestones do
      resources :tasks
    end
  end

end

app/models/task.rb
class Task < ActiveRecord::Base

	has_many :milestone_task_ids
	has_many :milestones , through: :milestone_task_ids

	def self.search(search)
	  where("Name ILIKE ?", "%#{search}%") 
	  # where("Description ILIKE ?", "%#{search}%")
	end
	
	paginates_per 4
	max_paginates_per 100

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    # @tasks = current_milestone.tasks
    @project = Project.find(params[:project_id])
    @milestone = Milestone.find(params[:milestone_id])
    
    if params[:search]
      @tasks = @milestone.tasks.search(params[:search]).order("created_at DESC").page(params[:page])
    else
      @tasks = @milestone.tasks.order('created_at ASC').page(params[:page])
    end

  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @task = Task.find(params[:id])
    @project = Project.find(params[:project_id])
    @milestone = Milestone.find(params[:milestone_id])
  end

  # GET /tasks/new
  def new
    # binding.pry
    @task = Task.new
    @project = Project.find(params[:project_id])
    @milestone = Milestone.find(params[:milestone_id])
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
    @project = Project.find(params[:project_id])
    @milestone = Milestone.find(params[:milestone_id])
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @project = Project.find(params[:project_id])
    @milestone = Milestone.find(params[:milestone_id])
    @task = @milestone.tasks.create(task_params)
    # @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to project_milestone_task_path(project_id: @project.id , milestone_id: @milestone.id , id: @task.id), notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    @project = Project.find(params[:project_id])
    @milestone = Milestone.find(params[:milestone_id])
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @project = Project.find(params[:project_id])
    @milestone = Milestone.find(params[:milestone_id])
    @task.destroy
    respond_to do |format|
      format.html { redirect_to project_milestone_tasks_path(project_id: @project.id , milestone_id: @milestone.id), notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:project_id])
    end

    def set_milestone
      @milestone = Milestone.find(params[:milestone_id])
    end

    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, :description, :start_date, :end_date, :status)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_for([@project,@milestone,@task]) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>
      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="item form-group bad">
    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Name :<span class="required">*</span>
    </label>
    <div class="col-md-8 col-sm-8 col-xs-12">
      <%= f.text_field :name , :placeholder => "Name" , :class => "form-control" , :data_validate_length_range =>"6" , :data_validate_words => "2" , :required => "required" , :type => "text"%>
    </div>
    <!-- <div class="alert">please put something here</div> -->
  </div>
  <br>
  <br>
  <br>
  
  <div class="item form-group bad">
    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Description : <span class="required">*</span>
    </label>
    <div class="col-md-8 col-sm-8 col-xs-12">
      <%= f.text_area :description , :class => "form-control" , :placeholder => "Description" , :data_validate_length_range =>"6" , :data_validate_words => "2" , :required => "required" , :type => "text"%>
    </div>
    <!-- <div class="alert">please put something here</div> -->
  </div>
  
  <br>
  <br>
  <br>
  <br>

  <div class="item form-group bad">
    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Select Status : <span class="required">*</span>
    </label>
    <div class="col-md-3 col-sm-8 col-xs-12">
    <%= f.select :status, [['Select Status'],['Active','active'],['Pending','pending'],['Completed','completed']] , :class => "form-control"%>
  </div>
  <div class="clearfix"></div>

  <br>

  <div class="item form-group bad">
    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Start Date : <span class="required">*</span>
    </label>
    <div class="col-md-8 col-sm-8 col-xs-12">
    <%= f.text_field :start_date , :class => "datepicker form-control" , :placeholder => "Start Date(mm/dd//yyyy)" , :data_validate_length_range =>"6" , :data_validate_words => "2" , :required => "required" %>
   </div>
    <!-- <div class="alert">please put something here</div> -->
  </div>

  <br>
  <br>
  
  <div class="item form-group bad">
    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">End Date : <span class="required">*</span>
    </label>
    <div class="col-md-8 col-sm-8 col-xs-12">
      <%= f.text_field :end_date , :class => "datepicker form-control" , :placeholder => "End Date(mm/dd//yyyy)" , :data_validate_length_range =>"6" , :data_validate_words => "2" , :required => "required" %>
    </div>
    <!-- <div class="alert">please put something here</div> -->
  </div>
  
  <br>
  <br>
  <br>
  <div class="col-md-8 col-sm-8 col-xs-12">
    <button class="col-md-offset-3 btn btn-info btn-block" type="submit">Submit</button>
  </div>
<% end %>


<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<script>

$(document).ready(function() {
    $(".datepicker").datepicker({
      dateFormat: "yy-mm-dd"
    });
});

 </script>

app/views/tasks/_search_task_form.html.erb
<%= form_tag(project_milestone_tasks_path, :method => "get", id: "search-form" , :class => "form-search form-horizontal pull-right col-md-3" ) do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search Projects", :class=> "form-control" %>
  <!-- <i class="glyphicon glyphicon-search project-search"></i> -->
<% end %>
<div class="clearfix"></div>

app/views/tasks/edit.html.erb
<div class="col-md-6 col-sm-12 col-xs-12 col-md-offset-3">
  <div class="pull-right">
    <%= link_to 'Show', project_milestone_task_path() , :class => "" %> |
    <%= link_to 'Back', project_milestone_tasks_path() , :class => "" %>
    <br>
    <br>
  </div>
</div>
<div class="col-md-6 col-sm-12 col-xs-12 col-md-offset-3">
  <div class="x_panel">
    <div class="x_content">
      <div class="dashboard-widget-content">
        <div class="col-md-6 col-md-offset-3 hidden-small">
          <h2 class="line_30">Edit Task</h2>
    		</div>
  		</div>
		</div>
		<br>
		<div class="text-center">
      <div class="row">
        <div class="col-lg-12 col-md-6 col-xs-6">
          <div class="form-group">
            <%= render 'form' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tasks/index.html.erb
<div class="container">
  <div class="pull-left">
    <i class="fa fa-arrow-left"></i> <%= link_to "Go To Projects"  , projects_path %> |  
      <%= link_to "Go To Milestones" , project_milestones_path(project_id: @project.id) %>
  </div>
  <div class="row tile_count">
    <%= render 'search_task_form' %>
    <div class="panel-heading flex-box flex-vertical-center-align justify-content-space-between">
      <h3 class="col-md-9">Tasks</h3>
    </div>
    <br>
    <div class="container">
      <div class="col-md-12">
        <table class="table table-list-search table-hover">
          <div class="pull-right">
            <% if can? :manage, Milestone %>
              <%= link_to 'New Task', new_project_milestone_task_path(@project,@milestone) , :class => "btn btn-info" %>
            <% end %>
          </div>
          <br>
          <br>
          <br>
          <thead>
            <tr>
              <th>Name</th>
              <th>Description</th>
              <th>Start date</th>
              <th>End date</th>
              <th>Status</th>
              <th colspan="1" style="width: 260px;">Manage</th>
            </tr>
          </thead>

          <tbody>
            <% @tasks.each do |task| %>
              <tr>
                <td><%= link_to task.name , project_milestone_task_path(project_id: @project.id , milestone_id: @milestone.id , id: task.id) %></td>
                <td><%= task.description %></td>
                <td><%= task.start_date %></td>
                <td><%= task.end_date %></td>
                <td><%= task.status %></td>
                <td><%= link_to raw("<span class='fa fa-wrench'></span>Edit"), edit_project_milestone_task_path(project_id: @project.id , milestone_id: @milestone.id , id: task.id) , :class => "btn btn-info btn-sm" %>
                    <%= link_to raw("<span class='fa fa-trash'></span>Delete"), project_milestone_task_path(project_id: @project.id , milestone_id: @milestone.id , id: task.id), method: :delete, data: { confirm: 'Are you sure?' } , :class => "btn btn-danger btn-sm" %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%= paginate @tasks %>
        <br>
        <br>
        <br>
      </div>
    </div>
  </div>
</div>

app/views/tasks/new.html.erb
<div class="col-md-6 col-sm-3 col-xs-12 col-md-offset-3">
	<div class="pull-right">
		<%= link_to 'Back', project_milestone_tasks_path(project_id: @project.id , milestone_id: @milestone.id) , :class => "" %>
		<br>
		<br>
	</div>
</div>
<div class="col-md-6 col-sm-3 col-xs-12 col-md-offset-3">
  <section class="panel">
		<div class="x_title">
      <h3 class="text-center"><strong>New Task</strong></h3>
      <div class="clearfix"></div>
		</div>
		<br>
    <div class="panel-body">
      <div class="text-center">
        <div class="row">
          <div class="col-lg-12 col-md-6 col-xs-6">
            <div class="form-group">
      				<%= render 'form' %>
      			</div>	
      		</div>
      	</div>
      </div>
    </div>
  </section>
</div>

app/views/tasks/show.html.erb
<div class="col-md-6 col-sm-3 col-xs-12 col-md-offset-3">
  <div class="pull-right">
    <%= link_to 'Edit', edit_project_milestone_task_path(project_id: @project.id , milestone_id: @milestone.id , id: @task.id) , :class => ""  %> |
    <%= link_to 'Back', project_milestone_tasks_path(project_id: @project.id , milestone_id: @milestone.id) , :class => ""  %>
    <br>
    <br>
  </div>
</div>
<div class="col-md-6 col-sm-3 col-xs-12 col-md-offset-3">
  <section class="panel">
    
    <div class="x_title">
      <h2>Task Description</h2>
      <div class="clearfix"></div>
    </div>
    <div class="panel-body">
      <h3 class="green"><i class="fa fa-paint-brush"></i> <%= @task.name %></h3>
      <br>
      <div class="project_detail">
        <div class="row">
          <div class="col-md-12">
            <div class="well col-md-12">
              <p>
                <strong>Description:</strong>
                <%= @task.description %>
              </p>
            </div>
          </div>
        </div>
        <div class="clearfix"></div>

        <p>
          <p class="title">Start Date : </p>
          <p><%= @task.start_date %> </p>
        </p>
        <p>
          <p class="title">End Date : </p>
          <p><%= @task.end_date %> </p>
        </p>
        <p>
          <p class="title">Status:</p>
          <p> <%= @task.status %> </p>
        </p>
      </div>
    </div>
  </section>
</div>