config/routes.rb
Rails.application.routes.draw do
  
  get 'home/index'

  default_url_options :host => "localhost"
  root 'home#index'

  devise_for :users, :controllers => {:registrations => "users/registrations"}

  resources :users, only: [:index]
  
  resources :projects do
    resources :milestones do
      resources :tasks
    end
  end

end

app/models/project.rb
class Project < ActiveRecord::Base

	has_many :user_project_ids
	has_many :users , through: :user_project_ids

	has_many :milestone_project_ids
  	has_many :milestones , through: :milestone_project_ids
	
	
	def self.search(search)
		
	  where("name ILIKE ?", "%#{search}%") 
	  # where("Description ILIKE ?", "%#{search}%")
	end

	paginates_per 4
	max_paginates_per 100
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_project ,only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /projects
  # GET /projects.json
  def index
    # binding.pry
    # @projects = current_user.projects
    if params[:search]
      @projects = current_user.projects.search(params[:search]).order("created_at DESC").page(params[:page])
    else
      @projects = current_user.projects.order('created_at ASC').page(params[:page])
    end
    # @projects = Project.all
    # @projects = Project.order(:name).
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    # binding.pry
    @project = Project.find(params[:id])
  end

  # GET /projects/new
  def new
    @users = User.all
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create

        # binding.pry
    @project = current_user.projects.create(project_params)
    # binding.pry
    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:uid, :name, :description, :start_date, :end_date)
    end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= javascript_include_tag "/assets/projects" %>
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>
      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="item form-group bad">
    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Name :<span class="required">*</span>
    </label>
    <div class="col-md-8 col-sm-8 col-xs-12">
      <%= f.text_field :name , :placeholder => "Name" , :class => "form-control" , :data_validate_length_range =>"6" , :data_validate_words => "2" , :required => "required" , :type => "text"%>
    </div>
    <!-- <div class="alert">please put something here</div> -->
  </div>
  <br>
  <br>
  <br>
  
  <div class="item form-group bad">
    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Description : <span class="required">*</span>
    </label>
    <div class="col-md-8 col-sm-8 col-xs-12">
      <%= f.text_area :description , :class => "form-control" , :placeholder => "Description" , :data_validate_length_range =>"6" , :data_validate_words => "2" , :required => "required" , :type => "text"%>
    </div>
    <!-- <div class="alert">please put something here</div> -->
  </div>
  
  <br>
  <br>
  <br>
  <br>
  <div class="item form-group bad">
    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Start Date : <span class="required">*</span>
    </label>
    <div class="col-md-8 col-sm-8 col-xs-12">
    <%= f.text_field :start_date , :class => "datepicker form-control" , :placeholder => "Start Date(mm/dd//yyyy)" , :data_validate_length_range =>"6" , :data_validate_words => "2" , :required => "required" %>
   </div>
    <!-- <div class="alert">please put something here</div> -->
  </div>

  <br>
  <br>

  <div class="item form-group bad">
    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">End Date : <span class="required">*</span>
    </label>
    <div class="col-md-8 col-sm-8 col-xs-12">
      <%= f.text_field :end_date , :class => "datepicker form-control" , :placeholder => "End Date(mm/dd//yyyy)" , :data_validate_length_range =>"6" , :data_validate_words => "2" , :required => "required" %>
    </div>
    <!-- <div class="alert">please put something here</div> -->
  </div>
  
  <br>
  <br>
  <div class="item form-group bad">
    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Select User : <span class="required">*</span>
    </label>
    <div class="col-md-3 col-sm-8 col-xs-12">
    <select name="users_list" id="" class="select2Field form-control pull-left" data-placeholder="Select User"></select>
  </div>
  <div class="clearfix"></div>

  <br>
  <div class="col-md-8 col-sm-8 col-xs-12">
    <button class="col-md-offset-3 btn btn-info btn-block" type="submit">Submit</button>
  </div>
<% end %>

<script type="text/javascript">
$(document).ready(function() {
  $(".js-example-basic-single").select2();
});
</script>

<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<script>

$(document).ready(function() {
    $(".datepicker").datepicker({
      dateFormat: "yy-mm-dd"
    });
});

 </script>

app/views/projects/_search_project_form.html.erb
<%= form_tag(projects_path, :method => "get", id: "search-form" , :class => "form-search form-horizontal pull-right col-md-3" ) do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search Projects", :class=> "form-control" %>
  <!-- <i class="glyphicon glyphicon-search project-search"></i> -->
<% end %>
<div class="clearfix"></div>

app/views/projects/edit.html.erb
<div class="col-md-6 col-sm-12 col-xs-12 col-md-offset-3">
  <div class="pull-right">
    <%= link_to 'Show', @project , :class => ""%> |
    <%= link_to 'Add Milestone', project_milestones_path(project_id: @project.id) , :class => "" %> |
    <%= link_to 'Back', projects_path , :class => "" %>
    <br>
    <br>
  </div>
</div>
<div class="col-md-6 col-sm-12 col-xs-12 col-md-offset-3">
  <div class="x_panel">
  	<div class="x_content">
      <div class="dashboard-widget-content">
        <div class="col-md-6 col-md-offset-3 hidden-small">
          <h2 class="line_30">Edit Project</h2>
    		</div>
  		</div>
		</div>
		<br>
	  <div class="text-center">
    	<div class="row">
        <div class="col-lg-12 col-md-6 col-xs-6">
        	<div class="form-group">
						<%= render 'form' %>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/projects/index.html.erb
<div class="container">
  <div class="row tile_count">
    <%= render 'search_project_form' %>
    <div class="panel-heading flex-box flex-vertical-center-align justify-content-space-between">
      <h3 class="col-md-9">Projects</h3>
    </div>
    <div class="container">
      <div class="col-md-12">
       <table class="table table-list-search table-hover">
          <div class="pull-right">
            <% if can? :manage, Project %>
              <%= link_to 'New Project', new_project_path , :class => "btn btn-info" %>
            <% end %>
          </div>
          <br>
          <br>
          <br>
          <thead>
            <tr>
              <th>Name</th>
              <th>Description</th>
              <th>Start date</th>
              <th>End date</th>
              <th colspan="1" style="width: 260px;">Manage</th>
            </tr>
          </thead>

          <tbody>
            <% @projects.each do |project| %>
              <tr>
                <td><%= link_to project.name, project  %></td>
                <td><%= project.description %></td>
                <td><%= project.start_date %></td>
                <td><%= project.end_date %></td>
                <td><%= link_to raw("<span class='fa fa-wrench'></span>Edit"), edit_project_path(project) , :class => "btn btn-info btn-sm" , :title => "Edit" %> &nbsp; &nbsp;
                    <%= link_to raw("<span class='fa fa-trash'></span>Delete"), project, method: :delete, data: { confirm: 'Are you sure?' } , :class => "btn btn-danger btn-sm" , :title => "Destroy" %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%= paginate @projects %>
        <br>
      </div>
    </div>
  </div>
</div>

app/views/projects/new.html.erb
<div class="col-md-6 col-sm-3 col-xs-12 col-md-offset-3">
  <div class="pull-right">
    <%= link_to 'Back to Index', projects_path , :class => "" %>
    <br>
    <br>
  </div>
</div> 
<div class="col-md-6 col-sm-3 col-xs-12 col-md-offset-3">
  <section class="panel">
    <div class="x_title">
      <h3 class="text-center"><strong>New Project</strong></h3>
      <div class="clearfix"></div>
    </div>
    <br>
    <div class="panel-body">
      <div class="text-center">
        <div class="row">
          <div class="col-lg-12 col-md-6 col-xs-6">
            <div class="form-group">
      				<%= render 'form' %>
      			</div>	
      		</div>
      	</div>
      </div>
    </div>
  </section>
</div>

app/views/projects/show.html.erb
<div class="col-md-6 col-sm-3 col-xs-12 col-md-offset-3">
  <div class="pull-right">
    <%= link_to 'Edit', edit_project_path(@project) , :class => "" %> |
    <%= link_to 'Back', projects_path , :class => "" %> | 
    <%= link_to 'Add Milestone' , new_project_milestone_path(project_id: @project.id) , :class => "" %> | 
    <%= link_to 'View Milestones' , project_milestones_path(project_id: @project.id) , :class => "" %>
    <br>
    <br>
  </div>
</div>
<div class="col-md-6 col-sm-3 col-xs-12 col-md-offset-3">
  <section class="panel">
    
    <div class="x_title">
      <h2>Project Description</h2>
      <div class="clearfix"></div>
    </div>
    <div class="panel-body">
      <h3 class="green"><i class="fa fa-paint-brush"></i> <%= @project.name %></h3>
      <br>
      <div class="project_detail">
        <div class="row">
          <div class="col-md-12">
            <div class="well col-md-12">
              <p class="title">Description : </p>
              <p><%= @project.description %></p>
            </div>
          </div>
        </div>
        <p class="title">Project Leader</p>
        <p>Tony Chicken</p>
        <p class="title">Start Date : </p>
        <p><%= @project.start_date %></p>
        <p class="title">End Date : </p>
        <p><%= @project.end_date %></p>
      </div>

      <br>
      <!-- <h5>Project files</h5>
      <ul class="list-unstyled project_files">
        <li><a href=""><i class="fa fa-file-word-o"></i> Functional-requirements.docx</a>
        </li>
        <li><a href=""><i class="fa fa-file-pdf-o"></i> UAT.pdf</a>
        </li>
        <li><a href=""><i class="fa fa-mail-forward"></i> Email-from-flatbal.mln</a>
        </li>
        <li><a href=""><i class="fa fa-picture-o"></i> Logo.png</a>
        </li>
        <li><a href=""><i class="fa fa-file-word-o"></i> Contract-10_12_2014.docx</a>
        </li>
      </ul>
      <br>

      <div class="text-center mtop20">
        <a href="#" class="btn btn-sm btn-primary">Add files</a>
        <a href="#" class="btn btn-sm btn-warning">Report contact</a>
      </div>
    </div> -->

  </section>

</div>


<!-- <div class="col-md-12 col-sm-12 col-xs-12">
  <div class="x_panel">
    
    <div class="x_content">
      <div class="dashboard-widget-content">
        <div class="col-md-6 col-md-offset-3 hidden-small">
          <h2 class="line_30">Project Details</h2>

          <table class="countries_list">
            <tbody>
              <tr>
                <td>Name : </td>
                <td class="fs15 fw700 text-right"><%= @project.name %></td>
              </tr>
              <tr>
                <td>Description : </td>
                <td class="fs15 fw700 text-right"><%= @project.description %></td>
              </tr>
              <tr>
                <td>Start Date : </td>
                <td class="fs15 fw700 text-right"><%= @project.start_date %></td>
              </tr>
              <tr>
                <td>End Date : </td>
                <td class="fs15 fw700 text-right"><%= @project.end_date %></td>
              </tr> -->
              <!-- <tr>
                <td>Britain</td>
                <td class="fs15 fw700 text-right">10%</td>
              </tr> -->
  <!--           </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div> -->



<!-- <div class="row">
  <div class="col-md-6">
  	
      <div class="container">
      	<div class="row">
        	<div class="col-xs-12">
          	<h3 class="text-center"><strong>Project Information</strong></h3>
        	</div>
        </div>
      </div>
      <br>
    	<div class="container">
		    <table class="table">
		    	<div class="col-md-offset-1">
						<p>
						  <div class="item form-group bad">
						    <label class="control-label col-md-2 col-sm-3 col-xs-12" for="name">Name : </label>
						    <div class="col-md-8 col-sm-8 col-xs-12">
						  		<%= @project.name %>
						  	</div>
						  </div>
						</p>
						<p>
						  <div class="item form-group bad">
						    <label class="control-label col-md-2 col-sm-3 col-xs-12" for="name">Description : </label>
						    <div class="col-md-8 col-sm-8 col-xs-12">
						    <%= @project.description %>
              </div>
						</p>
						<p>
						  <div class="item form-group bad">
						    <label class="control-label col-md-2 col-sm-3 col-xs-12" for="name">Start Date : </label>
                <%= @project.start_date %>
              </div>
						</p>
						<p>
						  <div class="item form-group bad">
						    <label class="control-label col-md-2 col-sm-3 col-xs-12" for="name">End Date : </label>
						    <%= @project.end_date %>
						  </div>
            </p>
          </div>
				</div> 
			</div>
		</div>
	</div>
</div> -->